[package]
name = "rfsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.28"
inotify = "0.10.1"
tokio = { version = "1.29.0", features = ["full", "tracing"] }
